### PR TITLE
Refactor and validate configuration file (#29, #119, #128)

### PR DESCRIPTION
**Pull request by ssciolla**
This PR aims to improve the ingestion of the `env` configuration file by changing the format to HJSON (allowing for greater customization), validating the contents of the file using JSON Schema, and nesting more variables, namely the `CANVAS` ones. I have also made changes to the `README.md` to reflect these changes, clarify some language, and add resources. The task list below provides some additional details. The PR aims to resolve issues #29, #119, and #128.

- [x] Add `hjson` and `jsonchema` to `requirements.txt`.
- [x] Nest Canvas variables inside a `CANVAS` object in the expected configuration file, and update usages in `COURSE_INVENTORY` and `CANVAS_ZOOM_MEETINGS` jobs.
- [x] Create and add a JSON Schema schema document as `env_schema.hjson` in the `config` directory.
- [x] Change `env_blank.json` to `env_blank.hjson`, remove unneeded variables, reorder variables, and add comments.
- [x] Within `environ.py`, import the schema and config file using `hjson` and use `jsonschema`'s `validate` function within a `try/except`.
- [x] Remove configuration details for Zoom-related variables from `README.md`.
- [x] Update `README.md` to reference `env.hjson`.
- [x] Restructure the `README.md`'s configuration variable table to have another column for the "Nested Key".

### CODE REVIEW

**Comment by pushyamig** [comment]
can you also put a sample of `env.hjson` in Box as well? make it simple for all of us

**Comment by pushyamig** [comment]
This Change Looks Good. I was able to run these jobs ["COURSE_INVENTORY", "MIVIDEO", "CANVAS_ZOOM_MEETINGS"]

**Comment by ssciolla** [comment]
> Looks good, I'd probably change environ.py to do a hjson.loads in the environ loop and remove the use of json in this module, but it's not a big deal. But then we'd just be consistent with hjson usage.

Thought about that, but I wasn't sure if I wanted to encourage use of HJSON syntax in the environment overrides. Seems better to just make people use standard JSON there; at which point, using `json` makes sense, though `hjson` probably wouldn't break anything. I'm gonna leave it alone for now; if it becomes annoying, we can consider changing it.

**Comment by jonespm** [comment]
Sure! I don't even know for this project if we'll use it at all, it's more something I'd like to add to MyLA anyway.

**Comment by ssciolla** [comment]
Thanks for the reviews! I'm merging this now.

**Pull request merged**
