### PR TITLE
#88 enabling SSL to support connections within MiServer

### LINKED ISSUE #88: Support connecting from MIServer instance MiDatabase by enabling SSL
The new MiServer set for the course inventory project the Database connection string needs to be enabled with SSL so that it can connect with MiDatabase instance

### PR DESCRIPTION
**Pull request by pushyamig**
I was able to test this on all the following scenarios
1. Miserver instance: Tesla
2. Localhost mysql DB instance
3. From Docker compose build

Resolves #88.

### CODE REVIEW

**Comment by ssciolla** [comment]
I don't think this is a bug, but an enhancement. We have not had to deal with SSL or certificates until now.

**Comment by pushyamig** [comment]
If you want to test this PR on Tesla, these are the steps need to be followed. Docker is already installed system-wide so this shouldn't be a problem running the docker command
1. ssh uniqname@tesla.dsc.umich.edu, log in  with you umich password
2. You will end up in the home directory(pwd), git clone project, cd into the project
3. add the `config/secrets/env.json` to the desired folder using 
`scp env.json uniqname@tesla.dsc.umich.edu:/home/<uniqname>`
4. Build`docker build -t <build-name>`
5. Run: `docker run <build-name>`

**Comment by lsloan** [comment]
@pushyamig, this PR has been approved, so maybe it's time to merge it and… :shipit:

**Comment by pushyamig** [comment]
this fix was put in in support of MIserver Setup for the project, but whether to have that or not is being in Question? So this change shouldn't hurt anything if we decided to drop the idea of running the process from MiServer. I will merge for now

**Pull request merged**
